#!/bin/bash
#
#its a simple cals perform add

#sum=$(( $1 + $2 ))
#echo "sum of $1 and $2 is equal to $sum "

if [ $2 = "+" ]
then
	ans=$(( $1 + $3 ))
elif [ $2 = "-" ]
then
	if [ $1 -lt $3 ]
	then 
		ans=$(( $3 - $1 ))
	else
		ans=$(( $1 - $3 ))
	fi
else
	echo "Invalid"
	exit #terminate the script
fi

echo " $1 $2 $3 = $ans"
