#!/bin/bash  
#above is the shebang
#
#its a simple cals perform add

#sum=$(( $1 + $2 ))
#echo "sum of $1 and $2 is equal to $sum "

function table() {
	for n in {1..10}
	do
		echo "$1 * $n = $(( $1 * $n ))"
	done
	while [ $n -le "20" ]
	do
		sleep 1 #used to wait for 1sec to execute the next
		echo "$1 * $n = $(( $1 * $n ))"
		$(( n++ ))
	done
		
	return 1
}

if [ $2 = "+" ]
then
	ans=$(( $1 + $3 ))
elif [ $2 = "-" ]
then
	if [ $1 -lt $3 ]
	then 
		ans=$(( $3 - $1 ))
	else
		ans=$(( $1 - $3 ))
	fi
elif [ $2 = "m" ]
then
	table $1
	exit 1
else
	echo "Invalid"
	exit #terminate the script
fi

echo " $1 $2 $3 = $ans"
