#!/bin/bash

#export PATH = $PATH:[file directory]
#chenge the file permission using chmod +x [file]

#cmd
pwd

#variable
uname=Mugil
echo "Hi $uname, Finally you here $uname"

#store and the cmd output
pdr=$(pwd)
#we can use also {} for variable output mostly 
#its used to attach extra details 
echo "$uname, your in $pdr ${pdr}_simp_cmd directory"

#cmd argv
#we use $0(0 is assigned to running shell script file),
#$1,$2,... for arguments passed to the scripts
echo "Hey, this the argv passed $1"

#read input 
read -p "Type something:" arg_var
echo "Hey, this the typed on passed $arg_var"

