apiVersion: v1
kind: Service
metadata:
        name: time-service
        labales:
                name: time-service
                lang: go
spec:
        type: LoadBalancer
        ports:
                - port: 8080
                  targetPort: 8080
        selector:
                name: time-pod
                lang: go
