apiVersion: v1
kind: Service
metadata:
        name: time-service
        lables:
                name: time-service
                lang: go
spec:
        type: NodePort
        port:
                - port: 8080
                  targetPort: 8080
                  nodePort: 30004
        selector:
                name: time-pod
                lang: go
